### ISSUE TITLE
no fedora 40 repo

### ISSUE THREAD

**Issue by wyup** [FyraLabs/devdocs#11]
Hello, i wanted to install openh264 related packages because fedora-cisco repo does not have any yet for 40/Branched/rawhide.

I came here but homepage install command fails:

```
sudo dnf install --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' --setopt='terra.gpgkey=https://repos.fyralabs.com/terra$releasever/key.asc' terra-release

Añadido repositorio terra desde https://repos.fyralabs.com/terra$releasever
terra                                                                                                                                                         0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'terra':
  - Status code: 404 for https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml (IP: 128.140.26.75)
Error: Failed to download metadata for repo 'terra': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Descartando repositorios: terra
Última comprobación de caducidad de metadatos hecha hace 0:27:32, el sáb 13 ene 2024 17:09:45.
No hay coincidencias para el argumento: terra-release
Error: No se pudo encontrar ningún resultado: terra-release
```
Also, there is nothing at:
[https://repos.fyralabs.com/terra40/](https://repos.fyralabs.com/terra40/)

I managed to install terra repo with this command i found at fedora.pkgs.org:

`dnf config-manager --add-repo https://terra.fyralabs.com/terra.repo`

however, dnf gives error when updating packages:

```
 Terra rawhide                                                                                                                                        ???% |   0.0   B/s |   0.0   B |  00m00s
>>> Status code: 404 for https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml (IP: 128.140.26.75) - https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml (IP: 128.140.26.75) - https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml (IP: 128.140.26.75) - https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml - repomd.xml
>>> Status code: 404 for https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml (IP: 128.140.26.75) - https://repos.fyralabs.com/terrarawhide/repodata/repomd.xml - repomd.xml
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```
So i disabled terra repo.

Please populate Fedora 40. Thank you very much.

**Comment by madonuko** [comment]
Please do not report any issues unrelated to the devdocs here. In this case, you should reported the issue at https://github.com/terrapkg/packages.

Anyway, according to the [Fedora Linux 40 Schedule](https://fedorapeople.org/groups/schedule/f-40/f-40-key-tasks.html), the upstream Fedora 40 repository will only be branched off on **2024-02-06**. We may branch off before this date but it's not guaranteed to happen (as stated in our [lifecycle page](https://developer.fyralabs.com/terra/lifecycle#branched-development-release)).

I'm still asking Lea if we can branch off earlier if possible, so stay tuned.

(N.B. we don't have a rawhide branch as of the time of writing.)

**Comment by madonuko** [comment]
Update: we now have a rawhide branch and we will mass-build all packages in around 8 hours in order to populate the repository.
